# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s3UZG5elkDbZAXWOhxpxAMUQijiT_xGu
"""

from posixpath import commonpath

import requests

from bs4 import BeautifulSoup



url="https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/gujarat-titans-vs-chennai-super-kings-1st-match-1359475/ball-by-ball-commentary"







r=requests.get(url)

htmlContent=r.content



#print(htmlContent) #HTML Content



#step2 HTML Parse



soup=BeautifulSoup(htmlContent, 'html.parser')



#print(soup.prettify)



#TITLE PRINT



title=soup.title

#print(title)



#get Classes of any element in Soup



#print(soup.find('p')['class'])



#print(soup.find("p",class_="ds-grow").get_text())



com=  soup.find_all("p",class_="ci-html-content ds-py-2 ds-px-3 xl:ds-pr-14")







for para in com:

  print(para.get_text())